### PR TITLE
hadoop-crypto-api -> crypto-serialization

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
@markelliot @uschi2000 beginning to split the crypto stuff from the hadoop stuff

**Comment by ellisjoe** [comment]
Questions:
1. cool with new project being called `crypto-serialization`?
2. package name either `com.palantir.crypto` or `com.palantir.crypto.serialization`

**Comment by uschi2000** [comment]
be careful with diamond dependencies when you change the project name.

**Comment by uschi2000** [comment]
package name: no real opinion. project name: happy with either.

**Comment by uschi2000** [comment]
but getting rid of the hadoop name makes sense for projects that don't have a hadoop dependency

**Review by markelliot — APPROVED** [review]

**Comment by markelliot** [comment]
it's not really just serialization, since you're also doing the actual decrypting stuff?

**Comment by markelliot** [comment]
it's really `crypto-store` or `crypto-storage`, and package should probably `com.palantir.crypto.(store|storage)`

**Comment by markelliot** [comment]
sorry, got the merge sequence a little wrong, but have cleaned up here (feel free to unroll my cleanup)

**Pull request merged**
